language: php

cache:
  directories:
    - vendor/

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

script:
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse --level 7 src
