language: php

cache:
  directories:
    - vendor/

php:
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

script: vendor/bin/phpunit
