name: Publish documentation to GH Pages

on:
  push:
    branches:
      - 'main'

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/jekyll-build-pages@v1
      with:
        source: docs
        destination: _site

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        cname: symfony-console-additions.efrane.com
